# Generated by Django 2.2.1 on 2020-04-21 20:40

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Android', 'ANDROID'), ('iOS', 'IOS'), ('Web', 'WEB'), ('Dashboard', 'DASHBOARD')], max_length=10, validators=[djchoices.choices.ChoicesValidator({'Android': 'ANDROID', 'Dashboard': 'DASHBOARD', 'Web': 'WEB', 'iOS': 'IOS'})])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'platform',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(blank=True, choices=[('OTH', 'OTHER')], max_length=5, null=True, validators=[djchoices.choices.ChoicesValidator({'OTH': 'OTHER'})])),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
