FROM ubuntu:16.04 as ert_base
RUN apt-get update --fix-missing
# utils only
RUN apt-get install openssl libssl1.0 build-essential tmux git lynx lsof nano htop curl -y
# python 3.6
RUN echo "deb http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial main" >> /etc/apt/sources.list
RUN echo "deb-src http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial main" >> /etc/apt/sources.list
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4AB0F789CBA31744CC7DA76A8CF63AD3F06FC659
RUN apt-get update
RUN apt-get install python3.6 -y
RUN apt-get install python3-dev python-pip python3-pip -y
RUN apt-get install python-dev python3.6-dev -y
RUN apt-get install python-setuptools -y
RUN rm /usr/bin/python3
RUN ln -s /usr/bin/python3.6 /usr/bin/python3
RUN python3 --version
# project dependencies
RUN apt-get install libpq-dev libpango1.0-0 libcairo2 libmysqlclient-dev mysql-client -y
RUN apt-get update --fix-missing && apt-get install -y tzdata gdal-bin
RUN mkdir /home/ubuntu
WORKDIR /home/ubuntu/
