version: "2.0"
volumes:
  psql_dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/aishwarydhare/Work/python/againstCOVID/ert-backend/docker/postgresql/data/
  psql_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/aishwarydhare/Work/python/againstCOVID/ert-backend/docker/postgresql/logs/
  drf_source:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/aishwarydhare/Work/python/againstCOVID/ert-backend/project
services:
  psqldb:
    build:
      context: postgresql
      dockerfile: Dockerfile.psql
    container_name: "psql"
    restart: always
    ports:
      - 5433:5433
    volumes:
      - psql_dbdata:/var/lib/postgresql/11/
      - psql_logs:/var/log/postgresql
    networks:
      - drf
  drf:
    build:
      context: ../
      dockerfile: docker/Dockerfile.drf
    restart: always
    container_name: "drf"
    ports:
      - 8001:8001
      - 8002:8002
      - 8003:8003
    volumes:
      - drf_source:/home/ubuntu/project
    depends_on:
      - "psqldb"
    networks:
      - drf
networks:
  drf:
    driver: bridge