FROM ert_base as ert_master
WORKDIR /home/ubuntu
RUN pip install --upgrade pip
COPY requirements requirements
RUN pip3 install -r requirements/development.txt

FROM ert_master
COPY project project
WORKDIR /home/ubuntu/project
EXPOSE 8001
EXPOSE 8002
EXPOSE 8003
CMD python3 manage.py runserver 0.0.0.0:8002
