# Generated by Django 2.2.1 on 2020-04-21 20:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import miscellaneous.common_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sid', models.CharField(default=miscellaneous.common_utils.generate_nanoid, max_length=15)),
                ('is_prepared', models.BooleanField(default=False)),
                ('prepared_at', models.DateTimeField()),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(editable=False, upload_to='')),
                ('s3_url', models.TextField(editable=False, max_length=50)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('report', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='reports.Report')),
            ],
            options={
                'db_table': 'uploaded_files',
            },
        ),
    ]
