# Generated by Django 2.2.1 on 2020-04-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
